export const FETCH_WONDERS_SUCCESS = "FETCH_WONDERS_SUCCESS";
export const FETCH_WONDERS_FAIL = "FETCH_WONDERS_FAIL";
export const FETCH_WONDERS_START = "FETCH_WONDERS_START";

export const SET_FILTER = "SET_FILTER";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT"; 